# Generated by Django 6.0 on 2025-12-25 07:43

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agents", "0001_initial"),
        ("settings_app", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="楽観的ロック用。更新ごとにインクリメントされる。",
                        verbose_name="バージョン",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(max_length=255, verbose_name="ファイル名"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "処理待ち"),
                            ("processing", "処理中"),
                            ("completed", "完了"),
                            ("failed", "失敗"),
                            ("partial", "一部成功"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状態",
                    ),
                ),
                (
                    "total_rows",
                    models.PositiveIntegerField(default=0, verbose_name="総行数"),
                ),
                (
                    "success_count",
                    models.PositiveIntegerField(default=0, verbose_name="成功件数"),
                ),
                (
                    "error_count",
                    models.PositiveIntegerField(default=0, verbose_name="エラー件数"),
                ),
                (
                    "error_log",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="行番号とエラー内容のリスト",
                        verbose_name="エラーログ",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="処理開始日時"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="処理完了日時"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_histories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="実行者",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                        verbose_name="テナント",
                    ),
                ),
            ],
            options={
                "verbose_name": "インポート履歴",
                "verbose_name_plural": "インポート履歴",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="楽観的ロック用。更新ごとにインクリメントされる。",
                        verbose_name="バージョン",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="氏名")),
                (
                    "name_kana",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="氏名（カナ）"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="メールアドレス"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="電話番号は正しい形式で入力してください",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="電話番号",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "男性"),
                            ("female", "女性"),
                            ("other", "その他"),
                            ("unspecified", "未回答"),
                        ],
                        default="unspecified",
                        max_length=15,
                        verbose_name="性別",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="生年月日"),
                ),
                ("address", models.TextField(blank=True, verbose_name="住所")),
                (
                    "current_company",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="現職企業"
                    ),
                ),
                (
                    "current_position",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="現職役職"
                    ),
                ),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("employed", "就業中"),
                            ("unemployed", "離職中"),
                            ("freelance", "フリーランス"),
                            ("student", "学生"),
                        ],
                        default="employed",
                        max_length=20,
                        verbose_name="就業状況",
                    ),
                ),
                (
                    "years_of_experience",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(50)],
                        verbose_name="経験年数",
                    ),
                ),
                (
                    "desired_salary",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="希望年収（万円）"
                    ),
                ),
                (
                    "desired_positions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="希望職種のリスト",
                        verbose_name="希望職種",
                    ),
                ),
                (
                    "desired_locations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="希望勤務地のリスト",
                        verbose_name="希望勤務地",
                    ),
                ),
                (
                    "can_relocate",
                    models.BooleanField(default=False, verbose_name="転勤可"),
                ),
                (
                    "available_from",
                    models.DateField(blank=True, null=True, verbose_name="入社可能日"),
                ),
                (
                    "skills",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="保有スキルのリスト",
                        verbose_name="スキル",
                    ),
                ),
                (
                    "qualifications",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="保有資格のリスト",
                        verbose_name="資格",
                    ),
                ),
                (
                    "education",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="最終学歴"
                    ),
                ),
                (
                    "resume_url",
                    models.URLField(blank=True, null=True, verbose_name="履歴書URL"),
                ),
                (
                    "cv_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="職務経歴書URL"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False,
                        help_text="アーカイブすると一覧に表示されない",
                        verbose_name="アーカイブ済み",
                    ),
                ),
                (
                    "agent_company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="candidates",
                        to="agents.agentcompany",
                        verbose_name="紹介元エージェント",
                    ),
                ),
                (
                    "registered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registered_candidates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="登録者",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="candidates",
                        to="settings_app.applicationsource",
                        verbose_name="流入経路",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                        verbose_name="テナント",
                    ),
                ),
            ],
            options={
                "verbose_name": "候補者",
                "verbose_name_plural": "候補者",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "email"),
                        name="unique_candidate_email_per_tenant",
                    )
                ],
            },
        ),
    ]
