# Generated by Django 6.0 on 2025-12-28 03:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0001_initial"),
        ("tenants", "0002_add_tenant_spreadsheet"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="楽観的ロック用。更新ごとにインクリメントされる。",
                        verbose_name="バージョン",
                    ),
                ),
                ("content", models.TextField(verbose_name="コメント内容")),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="削除済み"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="削除日時"
                    ),
                ),
                (
                    "edit_history",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="編集日時と内容のリスト",
                        verbose_name="編集履歴",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="投稿者",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="candidates.candidate",
                        verbose_name="候補者",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="削除者",
                    ),
                ),
                (
                    "mentions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="mentioned_in_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="メンション",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                        verbose_name="テナント",
                    ),
                ),
            ],
            options={
                "verbose_name": "コメント",
                "verbose_name_plural": "コメント",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["candidate", "created_at"],
                        name="candidates__candida_ae6260_idx",
                    ),
                    models.Index(
                        fields=["author", "created_at"],
                        name="candidates__author__610e2f_idx",
                    ),
                ],
            },
        ),
    ]
