# Generated by Django 6.0 on 2025-12-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/", verbose_name="アバター画像"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="department",
            field=models.CharField(blank=True, max_length=100, verbose_name="部署"),
        ),
        migrations.AddField(
            model_name="profile",
            name="position",
            field=models.CharField(blank=True, max_length=100, verbose_name="役職"),
        ),
    ]
