# Generated by Django 6.0 on 2025-12-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_avatar_profile_department_profile_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("system_admin", "システム管理者"),
                    ("consultant", "採用コンサルタント"),
                    ("client_admin", "人事担当者"),
                    ("hiring_manager", "採用責任者"),
                    ("client_recruiter", "企業担当者"),
                    ("interviewer", "面接官"),
                    ("agent", "人材紹介会社"),
                ],
                default="client_recruiter",
                max_length=20,
                verbose_name="ロール",
            ),
        ),
    ]
