# Generated by Django 6.0 on 2026-01-03 09:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_add_new_user_roles"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email_attempted",
                    models.EmailField(
                        max_length=254, verbose_name="試行メールアドレス"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="日時"
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="成功"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IPアドレス"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, verbose_name="ユーザーエージェント"),
                ),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="失敗理由"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ロケーション"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "ログイン履歴",
                "verbose_name_plural": "ログイン履歴",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="accounts_lo_user_id_85d75c_idx",
                    ),
                    models.Index(
                        fields=["email_attempted", "timestamp"],
                        name="accounts_lo_email_a_8b2f09_idx",
                    ),
                ],
            },
        ),
    ]
