# Generated by Django 6.0 on 2025-12-25 07:43

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agents", "0001_initial"),
        ("personas", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="楽観的ロック用。更新ごとにインクリメントされる。",
                        verbose_name="バージョン",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="求人タイトル"),
                ),
                (
                    "unique_code",
                    models.CharField(
                        help_text="社内管理用の識別コード",
                        max_length=50,
                        verbose_name="求人コード",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "下書き"),
                            ("active", "募集中"),
                            ("paused", "一時停止"),
                            ("closed", "募集終了"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "department",
                    models.CharField(blank=True, max_length=100, verbose_name="部門"),
                ),
                (
                    "team",
                    models.CharField(blank=True, max_length=100, verbose_name="チーム"),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "正社員"),
                            ("contract", "契約社員"),
                            ("part_time", "パート・アルバイト"),
                            ("temporary", "派遣社員"),
                            ("intern", "インターン"),
                        ],
                        default="full_time",
                        max_length=20,
                        verbose_name="雇用形態",
                    ),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=255, verbose_name="勤務地"),
                ),
                (
                    "remote_policy",
                    models.CharField(
                        blank=True,
                        help_text="例: フルリモート可、週2日出社、出社必須など",
                        max_length=100,
                        verbose_name="リモートワーク",
                    ),
                ),
                (
                    "salary_min",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="年収下限（万円）",
                    ),
                ),
                (
                    "salary_max",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="年収上限（万円）",
                    ),
                ),
                (
                    "salary_notes",
                    models.CharField(
                        blank=True,
                        help_text="例: 経験・スキルに応じて決定",
                        max_length=255,
                        verbose_name="年収補足",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="仕事内容")),
                ("requirements", models.TextField(blank=True, verbose_name="応募要件")),
                (
                    "preferred_requirements",
                    models.TextField(blank=True, verbose_name="歓迎要件"),
                ),
                (
                    "benefits",
                    models.TextField(blank=True, verbose_name="待遇・福利厚生"),
                ),
                (
                    "selection_process",
                    models.TextField(
                        blank=True,
                        help_text="例: 書類選考 → 一次面接 → 二次面接 → 最終面接",
                        verbose_name="選考プロセス",
                    ),
                ),
                (
                    "headcount",
                    models.PositiveIntegerField(default=1, verbose_name="募集人数"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="公開日時"
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="募集終了日時"
                    ),
                ),
                (
                    "deadline",
                    models.DateField(blank=True, null=True, verbose_name="応募締切日"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="社内メモ")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "hiring_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="採用責任者",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                        verbose_name="テナント",
                    ),
                ),
            ],
            options={
                "verbose_name": "求人",
                "verbose_name_plural": "求人",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobAgentCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="依頼日時"),
                ),
                (
                    "special_fee_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="設定しない場合はエージェント会社のデフォルト手数料率を適用",
                        max_digits=5,
                        null=True,
                        verbose_name="特別手数料率（%）",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "agent_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_jobs",
                        to="agents.agentcompany",
                        verbose_name="エージェント会社",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_agent_companies",
                        to="jobs.job",
                        verbose_name="求人",
                    ),
                ),
            ],
            options={
                "verbose_name": "求人エージェント",
                "verbose_name_plural": "求人エージェント",
                "ordering": ["-assigned_at"],
                "unique_together": {("job", "agent_company")},
            },
        ),
        migrations.AddField(
            model_name="job",
            name="agent_companies",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_jobs",
                through="jobs.JobAgentCompany",
                to="agents.agentcompany",
                verbose_name="依頼エージェント",
            ),
        ),
        migrations.CreateModel(
            name="JobPersona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=1, help_text="1が最優先", verbose_name="優先度"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_personas",
                        to="jobs.job",
                        verbose_name="求人",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="persona_jobs",
                        to="personas.persona",
                        verbose_name="ペルソナ",
                    ),
                ),
            ],
            options={
                "verbose_name": "求人ペルソナ",
                "verbose_name_plural": "求人ペルソナ",
                "ordering": ["priority"],
                "unique_together": {("job", "persona")},
            },
        ),
        migrations.AddField(
            model_name="job",
            name="personas",
            field=models.ManyToManyField(
                blank=True,
                related_name="jobs",
                through="jobs.JobPersona",
                to="personas.persona",
                verbose_name="ペルソナ",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.UniqueConstraint(
                fields=("tenant", "unique_code"), name="unique_job_code_per_tenant"
            ),
        ),
    ]
