# Generated by Django 6.0 on 2025-12-29 08:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0002_add_tenant_spreadsheet"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="操作日時"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "作成"),
                            ("update", "更新"),
                            ("delete", "削除"),
                            ("login", "ログイン"),
                            ("logout", "ログアウト"),
                            ("view", "閲覧"),
                            ("export", "エクスポート"),
                            ("import", "インポート"),
                            ("other", "その他"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="アクション",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="リソース種別"
                    ),
                ),
                (
                    "resource_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="リソースID"
                    ),
                ),
                (
                    "resource_repr",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="リソース表示名"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IPアドレス"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, verbose_name="ユーザーエージェント"),
                ),
                (
                    "path",
                    models.CharField(blank=True, max_length=500, verbose_name="パス"),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="メソッド"
                    ),
                ),
                (
                    "status_code",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="ステータスコード"
                    ),
                ),
                (
                    "changes",
                    models.JSONField(blank=True, default=dict, verbose_name="変更内容"),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="追加データ"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="tenants.tenant",
                        verbose_name="テナント",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "監査ログ",
                "verbose_name_plural": "監査ログ",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "timestamp"],
                        name="core_auditl_tenant__4440e3_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="core_auditl_user_id_7b678c_idx",
                    ),
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="core_auditl_resourc_a674ad_idx",
                    ),
                ],
            },
        ),
    ]
