# Generated by Django 6.0 on 2026-01-04 23:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_add_audit_log"),
        ("tenants", "0003_add_admin_spreadsheet_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        help_text="candidates, jobs, applications, interviews, users",
                        max_length=50,
                        verbose_name="エンティティタイプ",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("push", "DB → Spreadsheet"),
                            ("pull", "Spreadsheet → DB"),
                        ],
                        max_length=10,
                        verbose_name="同期方向",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待機中"),
                            ("in_progress", "実行中"),
                            ("success", "成功"),
                            ("partial", "一部成功"),
                            ("failed", "失敗"),
                            ("cancelled", "キャンセル"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "records_processed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="処理レコード数"
                    ),
                ),
                (
                    "records_created",
                    models.PositiveIntegerField(
                        default=0, verbose_name="作成レコード数"
                    ),
                ),
                (
                    "records_updated",
                    models.PositiveIntegerField(
                        default=0, verbose_name="更新レコード数"
                    ),
                ),
                (
                    "records_skipped",
                    models.PositiveIntegerField(
                        default=0, verbose_name="スキップレコード数"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="エラーメッセージ"),
                ),
                (
                    "error_details",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="エラー詳細"
                    ),
                ),
                ("started_at", models.DateTimeField(verbose_name="開始日時")),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完了日時"
                    ),
                ),
                (
                    "triggered_by",
                    models.CharField(
                        default="manual",
                        help_text="manual/auto/signal/webhook",
                        max_length=20,
                        verbose_name="トリガー",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_histories",
                        to="tenants.tenant",
                        verbose_name="テナント",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sync_histories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="実行ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "同期履歴",
                "verbose_name_plural": "同期履歴",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "started_at"],
                        name="core_synchi_tenant__10b2f6_idx",
                    ),
                    models.Index(
                        fields=["entity_type", "status"],
                        name="core_synchi_entity__0763ce_idx",
                    ),
                ],
            },
        ),
    ]
