# Generated by Django 6.0 on 2026-01-06 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_synchistory"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="synchistory",
            name="core_synchi_tenant__10b2f6_idx",
        ),
        migrations.RemoveIndex(
            model_name="synchistory",
            name="core_synchi_entity__0763ce_idx",
        ),
        migrations.DeleteModel(
            name="SyncHistory",
        ),
    ]
