# Generated by Django 6.0 on 2025-12-25 07:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="楽観的ロック用。更新ごとにインクリメントされる。",
                        verbose_name="バージョン",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="テナント名")),
                (
                    "code",
                    models.SlugField(
                        help_text="URLやサブドメインで使用可能な識別子",
                        unique=True,
                        verbose_name="テナントコード",
                    ),
                ),
                (
                    "logo_url",
                    models.URLField(blank=True, null=True, verbose_name="ロゴURL"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="無効にするとテナントのユーザーはログイン不可",
                        verbose_name="有効",
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("free", "無料プラン"),
                            ("starter", "スタータープラン"),
                            ("professional", "プロフェッショナルプラン"),
                            ("enterprise", "エンタープライズプラン"),
                        ],
                        default="free",
                        max_length=20,
                        verbose_name="契約プラン",
                    ),
                ),
                (
                    "max_users",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="このテナントで作成可能なユーザー数の上限",
                        verbose_name="最大ユーザー数",
                    ),
                ),
                (
                    "trial_ends_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="トライアル終了日"
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="テナント固有の設定をJSON形式で保存",
                        verbose_name="設定",
                    ),
                ),
            ],
            options={
                "verbose_name": "テナント",
                "verbose_name_plural": "テナント",
                "ordering": ["name"],
            },
        ),
    ]
