# Generated by Django 6.0 on 2025-12-27 10:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantSpreadsheet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="楽観的ロック用。更新ごとにインクリメントされる。",
                        verbose_name="バージョン",
                    ),
                ),
                (
                    "spreadsheet_id",
                    models.CharField(
                        help_text="Google SpreadsheetのID（URLの/d/以降の部分）",
                        max_length=255,
                        verbose_name="スプレッドシートID",
                    ),
                ),
                (
                    "spreadsheet_name",
                    models.CharField(
                        blank=True,
                        help_text="管理用の表示名",
                        max_length=255,
                        verbose_name="スプレッドシート名",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="無効にするとシートへの読み書きを停止",
                        verbose_name="有効",
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最終同期日時"
                    ),
                ),
                (
                    "sync_errors",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="直近のエラー情報をJSON形式で保存",
                        verbose_name="同期エラーログ",
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spreadsheet",
                        to="tenants.tenant",
                        verbose_name="テナント",
                    ),
                ),
            ],
            options={
                "verbose_name": "テナントスプレッドシート",
                "verbose_name_plural": "テナントスプレッドシート",
            },
        ),
    ]
