# Generated by Django 6.0 on 2026-01-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_add_tenant_spreadsheet"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantspreadsheet",
            name="admin_spreadsheet_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="ユーザー・パスワード管理用（コンサルタントのみ閲覧可）",
                max_length=255,
                verbose_name="管理用スプレッドシートID",
            ),
        ),
        migrations.AddField(
            model_name="tenantspreadsheet",
            name="admin_spreadsheet_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="管理用の表示名",
                max_length=255,
                verbose_name="管理用スプレッドシート名",
            ),
        ),
        migrations.AlterField(
            model_name="tenantspreadsheet",
            name="spreadsheet_id",
            field=models.CharField(
                help_text="候補者・求人・応募・面接データ用（顧客閲覧可）",
                max_length=255,
                verbose_name="業務用スプレッドシートID",
            ),
        ),
        migrations.AlterField(
            model_name="tenantspreadsheet",
            name="spreadsheet_name",
            field=models.CharField(
                blank=True,
                help_text="管理用の表示名",
                max_length=255,
                verbose_name="業務用スプレッドシート名",
            ),
        ),
    ]
