# Generated by Django 6.0 on 2026-01-06 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_add_admin_spreadsheet_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantspreadsheet",
            name="spreadsheet_id",
            field=models.CharField(
                help_text="Google SpreadsheetのID（URLの/d/以降の部分）",
                max_length=255,
                verbose_name="スプレッドシートID",
            ),
        ),
    ]
