# Generated by Django 6.0 on 2025-12-25 07:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="楽観的ロック用。更新ごとにインクリメントされる。",
                        verbose_name="バージョン",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="経路名")),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("direct", "直接応募"),
                            ("agent", "エージェント"),
                            ("job_board", "求人サイト"),
                            ("referral", "リファラル"),
                            ("sns", "SNS"),
                            ("other", "その他"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="経路タイプ",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="求人サイトやSNSの場合のURL",
                        null=True,
                        verbose_name="URL",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="表示順序"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="空欄の場合は全テナント共通",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application_sources",
                        to="tenants.tenant",
                        verbose_name="テナント",
                    ),
                ),
            ],
            options={
                "verbose_name": "応募経路",
                "verbose_name_plural": "応募経路",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="楽観的ロック用。更新ごとにインクリメントされる。",
                        verbose_name="バージョン",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="テンプレート名"),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("interview_invitation", "面接案内"),
                            ("interview_reminder", "面接リマインダー"),
                            ("interview_feedback", "面接結果"),
                            ("offer_letter", "内定通知"),
                            ("rejection", "不採用通知"),
                            ("welcome", "ウェルカムメール"),
                            ("custom", "カスタム"),
                        ],
                        default="custom",
                        max_length=30,
                        verbose_name="テンプレートタイプ",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="変数: {{candidate_name}}, {{job_title}} など",
                        max_length=255,
                        verbose_name="件名",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="変数: {{candidate_name}}, {{job_title}}, {{interview_date}} など",
                        verbose_name="本文",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="同じタイプのデフォルトテンプレート",
                        verbose_name="デフォルト",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                        verbose_name="テナント",
                    ),
                ),
            ],
            options={
                "verbose_name": "メールテンプレート",
                "verbose_name_plural": "メールテンプレート",
                "ordering": ["template_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="StatusSetting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="楽観的ロック用。更新ごとにインクリメントされる。",
                        verbose_name="バージョン",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("application", "応募ステータス"),
                            ("interview", "面接ステータス"),
                            ("job", "求人ステータス"),
                        ],
                        max_length=20,
                        verbose_name="カテゴリ",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="ステータス名")),
                (
                    "code",
                    models.CharField(
                        help_text="システム内部で使用するコード",
                        max_length=30,
                        verbose_name="ステータスコード",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="表示順序"),
                ),
                (
                    "color",
                    models.CharField(
                        default="gray",
                        help_text="Tailwind CSSのカラー名（例: blue, green, red）",
                        max_length=20,
                        verbose_name="表示色",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "is_terminal",
                    models.BooleanField(
                        default=False,
                        help_text="このステータスで処理が終了するかどうか",
                        verbose_name="終了ステータス",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                        verbose_name="テナント",
                    ),
                ),
            ],
            options={
                "verbose_name": "ステータス設定",
                "verbose_name_plural": "ステータス設定",
                "ordering": ["category", "display_order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "category", "code"),
                        name="unique_status_code_per_tenant_category",
                    )
                ],
            },
        ),
    ]
