# Generated by Django 6.0 on 2025-12-31 08:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings_app", "0001_initial"),
        ("tenants", "0002_add_tenant_spreadsheet"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpreadsheetConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="楽観的ロック用。更新ごとにインクリメントされる。",
                        verbose_name="バージョン",
                    ),
                ),
                (
                    "spreadsheet_id",
                    models.CharField(
                        help_text="GoogleスプレッドシートのID（URLから取得）",
                        max_length=255,
                        verbose_name="スプレッドシートID",
                    ),
                ),
                (
                    "spreadsheet_url",
                    models.URLField(
                        blank=True,
                        help_text="https://docs.google.com/spreadsheets/d/xxxxx/edit",
                        verbose_name="スプレッドシートURL",
                    ),
                ),
                (
                    "spreadsheet_name",
                    models.CharField(
                        blank=True,
                        help_text="識別用の名前",
                        max_length=255,
                        verbose_name="スプレッドシート名",
                    ),
                ),
                (
                    "credentials_json",
                    models.TextField(
                        blank=True,
                        help_text="Google Cloud サービスアカウントのJSONキー",
                        verbose_name="認証情報（JSON）",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="連携有効"),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("pending", "未接続"),
                            ("connected", "接続済み"),
                            ("syncing", "同期中"),
                            ("error", "エラー"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="同期ステータス",
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最終同期日時"
                    ),
                ),
                (
                    "last_sync_error",
                    models.TextField(blank=True, verbose_name="最終エラー"),
                ),
                (
                    "sync_candidates",
                    models.BooleanField(default=True, verbose_name="候補者を同期"),
                ),
                (
                    "sync_jobs",
                    models.BooleanField(default=True, verbose_name="求人を同期"),
                ),
                (
                    "sync_applications",
                    models.BooleanField(default=True, verbose_name="応募を同期"),
                ),
                (
                    "sync_interviews",
                    models.BooleanField(default=True, verbose_name="面接を同期"),
                ),
                (
                    "auto_sync_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="アプリ側の変更を自動的にスプレッドシートに反映",
                        verbose_name="自動同期有効",
                    ),
                ),
                (
                    "sync_interval_minutes",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="スプレッドシートからの変更を取り込む間隔",
                        verbose_name="同期間隔（分）",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                        verbose_name="テナント",
                    ),
                ),
            ],
            options={
                "verbose_name": "スプレッドシート連携",
                "verbose_name_plural": "スプレッドシート連携",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "spreadsheet_id"),
                        name="unique_spreadsheet_per_tenant",
                    )
                ],
            },
        ),
    ]
