# Generated by Django 6.0 on 2026-01-05 00:17

import apps.core.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings_app", "0002_add_spreadsheet_connection"),
        ("tenants", "0003_add_admin_spreadsheet_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spreadsheetconnection",
            name="credentials_json",
            field=apps.core.fields.EncryptedTextField(
                blank=True,
                help_text="Google Cloud サービスアカウントのJSONキー（暗号化して保存）",
                verbose_name="認証情報（JSON）",
            ),
        ),
        migrations.CreateModel(
            name="SheetDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="楽観的ロック用。更新ごとにインクリメントされる。",
                        verbose_name="バージョン",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("candidates", "候補者"),
                            ("jobs", "求人"),
                            ("applications", "応募"),
                            ("interviews", "面接"),
                            ("users", "ユーザー"),
                        ],
                        help_text="同期対象のデータタイプ",
                        max_length=50,
                        verbose_name="エンティティタイプ",
                    ),
                ),
                (
                    "sheet_name",
                    models.CharField(
                        help_text="スプレッドシート上のシート名",
                        max_length=100,
                        verbose_name="シート名",
                    ),
                ),
                (
                    "headers",
                    models.JSONField(
                        default=list,
                        help_text="シートのヘッダー行（順序付きリスト）",
                        verbose_name="ヘッダー定義",
                    ),
                ),
                (
                    "column_mapping",
                    models.JSONField(
                        default=dict,
                        help_text="DBフィールド名 → シートカラム名のマッピング",
                        verbose_name="カラムマッピング",
                    ),
                ),
                (
                    "reverse_mapping",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="シートカラム名 → DBフィールド名（pull時に使用）",
                        verbose_name="逆マッピング",
                    ),
                ),
                (
                    "validation_rules",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSONSchema形式のバリデーション定義",
                        verbose_name="バリデーションルール",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                        verbose_name="テナント",
                    ),
                ),
            ],
            options={
                "verbose_name": "シート定義",
                "verbose_name_plural": "シート定義",
                "ordering": ["entity_type"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "entity_type"),
                        name="unique_sheet_definition_per_tenant",
                    )
                ],
            },
        ),
    ]
