# Generated by Django 6.0 on 2026-01-06 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settings_app", "0003_alter_spreadsheetconnection_credentials_json_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="sheetdefinition",
            name="unique_sheet_definition_per_tenant",
        ),
        migrations.DeleteModel(
            name="SheetDefinition",
        ),
    ]
