# Generated by Django 6.0 on 2025-12-25 07:43

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentCompany",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="楽観的ロック用。更新ごとにインクリメントされる。",
                        verbose_name="バージョン",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="会社名")),
                (
                    "code",
                    models.CharField(
                        help_text="社内管理用の一意識別子",
                        max_length=50,
                        unique=True,
                        verbose_name="会社コード",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="連絡先メール"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="連絡先電話番号"
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="担当者名"
                    ),
                ),
                (
                    "fee_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=30.0,
                        help_text="成功報酬の割合（年収の何%）",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="紹介手数料率（%）",
                    ),
                ),
                (
                    "contract_start_date",
                    models.DateField(blank=True, null=True, verbose_name="契約開始日"),
                ),
                (
                    "contract_end_date",
                    models.DateField(blank=True, null=True, verbose_name="契約終了日"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="無効にすると新規紹介を受け付けない",
                        verbose_name="有効",
                    ),
                ),
                (
                    "is_preferred",
                    models.BooleanField(
                        default=False,
                        help_text="優先的に案件を紹介するパートナー",
                        verbose_name="優先パートナー",
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="住所")),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="Webサイト"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "total_candidates",
                    models.PositiveIntegerField(default=0, verbose_name="紹介候補者数"),
                ),
                (
                    "total_placements",
                    models.PositiveIntegerField(default=0, verbose_name="採用決定数"),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="空欄の場合は全テナント共通",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_companies",
                        to="tenants.tenant",
                        verbose_name="テナント",
                    ),
                ),
            ],
            options={
                "verbose_name": "エージェント会社",
                "verbose_name_plural": "エージェント会社",
                "ordering": ["name"],
            },
        ),
    ]
