# Generated by Django 6.0 on 2025-12-25 07:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("candidates", "0001_initial"),
        ("jobs", "0001_initial"),
        ("settings_app", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="楽観的ロック用。更新ごとにインクリメントされる。",
                        verbose_name="バージョン",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "新規応募"),
                            ("document_screening", "書類選考中"),
                            ("document_passed", "書類通過"),
                            ("document_rejected", "書類不合格"),
                            ("interview_scheduled", "面接調整中"),
                            ("interviewing", "面接中"),
                            ("offer_pending", "内定検討中"),
                            ("offer_made", "内定"),
                            ("offer_accepted", "内定承諾"),
                            ("offer_declined", "内定辞退"),
                            ("rejected", "不採用"),
                            ("withdrawn", "辞退"),
                            ("on_hold", "保留"),
                        ],
                        default="new",
                        max_length=30,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="応募日時"),
                ),
                (
                    "evaluation_score",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="1〜5の5段階評価",
                        null=True,
                        verbose_name="評価スコア",
                    ),
                ),
                (
                    "evaluation_notes",
                    models.TextField(blank=True, verbose_name="評価コメント"),
                ),
                (
                    "offer_salary",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="提示年収（万円）"
                    ),
                ),
                (
                    "offer_made_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="内定日"),
                ),
                (
                    "offer_deadline",
                    models.DateField(
                        blank=True, null=True, verbose_name="内定回答期限"
                    ),
                ),
                (
                    "offer_notes",
                    models.TextField(blank=True, verbose_name="内定条件メモ"),
                ),
                (
                    "joined_at",
                    models.DateField(blank=True, null=True, verbose_name="入社日"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="candidates.candidate",
                        verbose_name="候補者",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="jobs.job",
                        verbose_name="求人",
                    ),
                ),
                (
                    "registered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registered_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="登録者",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applications",
                        to="settings_app.applicationsource",
                        verbose_name="応募経路",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                        verbose_name="テナント",
                    ),
                ),
            ],
            options={
                "verbose_name": "応募",
                "verbose_name_plural": "応募",
                "ordering": ["-applied_at"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="楽観的ロック用。更新ごとにインクリメントされる。",
                        verbose_name="バージョン",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("new", "新規応募"),
                            ("document_screening", "書類選考中"),
                            ("document_passed", "書類通過"),
                            ("document_rejected", "書類不合格"),
                            ("interview_scheduled", "面接調整中"),
                            ("interviewing", "面接中"),
                            ("offer_pending", "内定検討中"),
                            ("offer_made", "内定"),
                            ("offer_accepted", "内定承諾"),
                            ("offer_declined", "内定辞退"),
                            ("rejected", "不採用"),
                            ("withdrawn", "辞退"),
                            ("on_hold", "保留"),
                        ],
                        max_length=30,
                        verbose_name="変更前ステータス",
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("new", "新規応募"),
                            ("document_screening", "書類選考中"),
                            ("document_passed", "書類通過"),
                            ("document_rejected", "書類不合格"),
                            ("interview_scheduled", "面接調整中"),
                            ("interviewing", "面接中"),
                            ("offer_pending", "内定検討中"),
                            ("offer_made", "内定"),
                            ("offer_accepted", "内定承諾"),
                            ("offer_declined", "内定辞退"),
                            ("rejected", "不採用"),
                            ("withdrawn", "辞退"),
                            ("on_hold", "保留"),
                        ],
                        max_length=30,
                        verbose_name="変更後ステータス",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="変更理由・メモ")),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="applications.application",
                        verbose_name="応募",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="status_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="変更者",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                        verbose_name="テナント",
                    ),
                ),
            ],
            options={
                "verbose_name": "ステータス履歴",
                "verbose_name_plural": "ステータス履歴",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.UniqueConstraint(
                fields=("candidate", "job"), name="unique_application_per_candidate_job"
            ),
        ),
    ]
