# Generated by Django 6.0 on 2026-01-03 09:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0002_add_tenant_spreadsheet"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="楽観的ロック用。更新ごとにインクリメントされる。",
                        verbose_name="バージョン",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="設定名")),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("monthly_summary", "月次サマリー"),
                            ("weekly_progress", "週次進捗"),
                            ("bimonthly_comparison", "過去2ヶ月比較"),
                            ("semi_annual", "半期レビュー"),
                            ("custom", "カスタム"),
                        ],
                        max_length=30,
                        verbose_name="レポートタイプ",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("csv", "CSV"),
                            ("excel", "Excel"),
                            ("html", "HTML（メール本文）"),
                        ],
                        default="pdf",
                        max_length=10,
                        verbose_name="形式",
                    ),
                ),
                (
                    "recipients",
                    models.JSONField(
                        default=list,
                        help_text="配信先メールアドレスのリスト",
                        verbose_name="配信先メールアドレス",
                    ),
                ),
                (
                    "cc_recipients",
                    models.JSONField(blank=True, default=list, verbose_name="CC配信先"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "include_charts",
                    models.BooleanField(default=True, verbose_name="グラフを含む"),
                ),
                (
                    "include_details",
                    models.BooleanField(default=False, verbose_name="詳細データを含む"),
                ),
                (
                    "cron_expression",
                    models.CharField(
                        blank=True,
                        help_text="カスタムスケジュール用（例: 0 9 1 * *）",
                        max_length=100,
                        verbose_name="Cron式",
                    ),
                ),
                (
                    "last_run_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最終実行日時"
                    ),
                ),
                (
                    "last_run_status",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="最終実行結果"
                    ),
                ),
                (
                    "last_run_error",
                    models.TextField(blank=True, verbose_name="最終実行エラー"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_report_schedules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                        verbose_name="テナント",
                    ),
                ),
            ],
            options={
                "verbose_name": "定期レポート設定",
                "verbose_name_plural": "定期レポート設定",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="楽観的ロック用。更新ごとにインクリメントされる。",
                        verbose_name="バージョン",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待機中"),
                            ("running", "実行中"),
                            ("completed", "完了"),
                            ("failed", "失敗"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="開始日時"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完了日時"
                    ),
                ),
                (
                    "report_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="reports/%Y/%m/",
                        verbose_name="レポートファイル",
                    ),
                ),
                (
                    "recipients_sent",
                    models.JSONField(default=list, verbose_name="送信先"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="エラーメッセージ"),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                        verbose_name="テナント",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="reports.reportschedule",
                        verbose_name="スケジュール",
                    ),
                ),
            ],
            options={
                "verbose_name": "レポート実行履歴",
                "verbose_name_plural": "レポート実行履歴",
                "ordering": ["-started_at"],
            },
        ),
    ]
