# Generated by Django 6.0 on 2025-12-25 07:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applications", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="楽観的ロック用。更新ごとにインクリメントされる。",
                        verbose_name="バージョン",
                    ),
                ),
                (
                    "interview_type",
                    models.CharField(
                        choices=[
                            ("phone", "電話面接"),
                            ("video", "Web面接"),
                            ("in_person", "対面面接"),
                            ("technical", "技術面接"),
                            ("final", "最終面接"),
                        ],
                        default="video",
                        max_length=20,
                        verbose_name="面接タイプ",
                    ),
                ),
                (
                    "interview_round",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="何次面接か（1次、2次...）",
                        verbose_name="面接回数",
                    ),
                ),
                ("scheduled_at", models.DateTimeField(verbose_name="面接予定日時")),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=60, verbose_name="予定時間（分）"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="対面の場合は住所、Webの場合はURL",
                        max_length=500,
                        verbose_name="場所/URL",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "予定"),
                            ("confirmed", "確定"),
                            ("in_progress", "実施中"),
                            ("completed", "完了"),
                            ("cancelled", "キャンセル"),
                            ("no_show", "欠席"),
                            ("rescheduled", "再調整"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("pending", "評価待ち"),
                            ("passed", "合格"),
                            ("failed", "不合格"),
                            ("hold", "保留"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="結果",
                    ),
                ),
                (
                    "evaluation_score",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="1〜5の5段階評価",
                        null=True,
                        verbose_name="評価スコア",
                    ),
                ),
                (
                    "evaluation_criteria",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="項目別評価をJSON形式で保存",
                        verbose_name="評価項目",
                    ),
                ),
                (
                    "feedback",
                    models.TextField(
                        blank=True,
                        help_text="候補者への伝達事項",
                        verbose_name="フィードバック",
                    ),
                ),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True,
                        help_text="社内のみで共有する情報",
                        verbose_name="社内メモ",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="実際の開始時刻"
                    ),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="実際の終了時刻"
                    ),
                ),
                (
                    "reminder_sent",
                    models.BooleanField(
                        default=False, verbose_name="リマインダー送信済み"
                    ),
                ),
                (
                    "additional_interviewers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="additional_interviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="同席者",
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="applications.application",
                        verbose_name="応募",
                    ),
                ),
                (
                    "interviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conducted_interviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="面接官",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                        verbose_name="テナント",
                    ),
                ),
            ],
            options={
                "verbose_name": "面接",
                "verbose_name_plural": "面接",
                "ordering": ["-scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="InterviewFeedbackRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="楽観的ロック用。更新ごとにインクリメントされる。",
                        verbose_name="バージョン",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="入力完了"),
                ),
                (
                    "evaluation_score",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="評価スコア"
                    ),
                ),
                (
                    "feedback",
                    models.TextField(blank=True, verbose_name="フィードバック"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="入力完了日時"
                    ),
                ),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_requests",
                        to="interviews.interview",
                        verbose_name="面接",
                    ),
                ),
                (
                    "requested_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="依頼先",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                        verbose_name="テナント",
                    ),
                ),
            ],
            options={
                "verbose_name": "フィードバック依頼",
                "verbose_name_plural": "フィードバック依頼",
                "ordering": ["-created_at"],
                "unique_together": {("interview", "requested_to")},
            },
        ),
    ]
