# Generated by Django 6.0 on 2025-12-25 07:43

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="楽観的ロック用。更新ごとにインクリメントされる。",
                        verbose_name="バージョン",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="ペルソナ名")),
                ("description", models.TextField(blank=True, verbose_name="詳細説明")),
                (
                    "is_template",
                    models.BooleanField(
                        default=False,
                        help_text="テンプレートとして保存すると他の求人で再利用可能",
                        verbose_name="テンプレート",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "age_min",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(18),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="最小年齢",
                    ),
                ),
                (
                    "age_max",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(18),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="最大年齢",
                    ),
                ),
                (
                    "experience_years_min",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(50)],
                        verbose_name="最小経験年数",
                    ),
                ),
                (
                    "experience_years_max",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(50)],
                        verbose_name="最大経験年数",
                    ),
                ),
                (
                    "required_skills",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="必須スキルのリスト",
                        verbose_name="必須スキル",
                    ),
                ),
                (
                    "preferred_skills",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="歓迎スキルのリスト",
                        verbose_name="歓迎スキル",
                    ),
                ),
                (
                    "education_level",
                    models.CharField(
                        choices=[
                            ("none", "不問"),
                            ("high_school", "高卒以上"),
                            ("vocational", "専門卒以上"),
                            ("associate", "短大卒以上"),
                            ("bachelor", "大卒以上"),
                            ("master", "修士以上"),
                            ("doctor", "博士以上"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="学歴要件",
                    ),
                ),
                (
                    "personality_traits",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="求める性格特性のリスト",
                        verbose_name="人物像・性格",
                    ),
                ),
                (
                    "work_style",
                    models.TextField(
                        blank=True,
                        help_text="求める働き方の説明",
                        verbose_name="働き方",
                    ),
                ),
                (
                    "motivation",
                    models.TextField(
                        blank=True,
                        help_text="求める志向性・モチベーション",
                        verbose_name="志向性",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_personas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                        verbose_name="テナント",
                    ),
                ),
            ],
            options={
                "verbose_name": "ペルソナ",
                "verbose_name_plural": "ペルソナ",
                "ordering": ["name"],
            },
        ),
    ]
