# Generated by Django 6.0 on 2025-12-25 07:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="楽観的ロック用。更新ごとにインクリメントされる。",
                        verbose_name="バージョン",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("new_application", "新規応募"),
                            ("status_change", "ステータス変更"),
                            ("interview_reminder", "面接リマインド"),
                            ("interview_scheduled", "面接スケジュール確定"),
                            ("interview_completed", "面接完了"),
                            ("feedback_request", "フィードバック依頼"),
                            ("pending_deadline", "対応期限"),
                            ("offer_made", "内定通知"),
                            ("offer_response", "内定回答"),
                            ("system", "システム通知"),
                        ],
                        default="system",
                        max_length=30,
                        verbose_name="通知タイプ",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "低"),
                            ("normal", "通常"),
                            ("high", "高"),
                            ("urgent", "緊急"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="優先度",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="タイトル")),
                ("message", models.TextField(blank=True, verbose_name="本文")),
                (
                    "link",
                    models.CharField(
                        blank=True,
                        help_text="クリック時の遷移先URL",
                        max_length=500,
                        verbose_name="リンク先",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="既読")),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="既読日時"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="通知に関連する追加情報",
                        verbose_name="追加データ",
                    ),
                ),
                (
                    "related_object_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="関連オブジェクトタイプ"
                    ),
                ),
                (
                    "related_object_id",
                    models.CharField(
                        blank=True, max_length=36, verbose_name="関連オブジェクトID"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="tenants.tenant",
                        verbose_name="テナント",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="通知先ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "通知",
                "verbose_name_plural": "通知",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read", "-created_at"],
                        name="notificatio_user_id_f2ad08_idx",
                    )
                ],
            },
        ),
    ]
